### ISSUE TITLE
The test effect is affected by the initial position of the robot

### ISSUE THREAD

**Issue by xxx-007** [sayantanauddy/hierarchical_bipedal_controller#6]
Hello,I have a question about the test result.

Does your result affect  by  the initial position of the robot? If you change the robot's position ,will you still have good test effect? If you cannot get good test effect ,how do you change this condition?

At present , I am training robot using vrep  for reinforcement learning ,but my robot is affected by the initial position of the robot .If I test the robot which position is the position in the train scene,then my robot is able to walk straightly,but if i test the robot which position is not the position in the train  scene,then my robot is not able to walk straightly.What should I do to change this ?

Thank you very much!

**Comment by sayantanauddy** [comment]
Sorry for the late reply. This project is not actively maintained anymore. 
As far as I remember, I always started the walk after the robot reached a stable pre-defined pose (with knees slightly bent) from a completely upright stance. In order to walk stably, this starting position is very important and I don't think that a stable walk is possible from any arbitrary starting pose. However, there might be other kinds of poses from which the robot can also start to walk. If the focus of your work is on the stability of the walk, then perhaps the starting pose I used would be sufficient for you as well. If not, then maybe you need a separate optimization process to tune the starting pose.
